// client/src/signup/views/Signup.vue
<template>
    <div class='h-full w-full flex items-center justify-center'>
      <div>
        <h1 class='mb-8 text-bolder text-3xl'>Sign up</h1>
        <form @submit.prevent>
          <div class='mb-4'>
              <label class='block' for="username">Username</label>
              <input class='input' type="text" name="username" v-model="form.username" />
          </div>
          <div class='mb-4'>
              <label class='block' for="password">Password</label>
              <input class='input' type="password" name="password" v-model="form.password" />
          </div>
          <div class='text-center' @click="createAccount">
              <button class='btn'>Create account</button>
          </div>
        </form>
      </div>
    </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";
import { UserForm } from "../../common/types";
import { signupUser } from "../composables/signup";

const form = ref<UserForm>({
  username: "",
  password: ""
})

async function createAccount() {
  try {
    await signupUser(form.value);
  } catch(e) {
    console.error(e);
  }
}
</script>

// client/src/pages/signup/Signup.tsx
import { Component, createSignal } from 'solid-js';
import {httpClient} from '../../common/http/http-client';

const Signup: Component = () => {
    const [username, setUsername] = createSignal('');
    const [password, setPassword] = createSignal('');

    async function submit() {
        try {
            const form = {
                username: username(),
                password: password()
            }
            const response = await httpClient.post('users', form);
            console.log('response', response);
        } catch(e) {
            console.error('error', e);
        }
    }
  return (
    <div class='h-full w-full flex items-center justify-center'>
      <div style="transform: translateY(-100px)">
        <h1 class='mb-8 text-bolder text-3xl'>Sign up</h1>
        <form onSubmit={(e) => e.preventDefault()}>
          <div class='mb-4'>
              <label class='block' for="username">Username</label>
              <input class='input' type="text" name="username" value={username()} onInput={(e) => setUsername(e.currentTarget.value)}></input>
          </div>
          <div class='mb-4'>
              <label class='block' for="password">Password</label>
              <input class='input' type="text" name="password" value={password()} onInput={(e) => setPassword(e.currentTarget.value)}></input>
          </div>
          <div class='text-center'>
              <button class='btn' onClick={submit}>Create account</button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Signup;
